### ISSUE TITLE
[Issue] Teleport to the closest nucleus fix required

### ISSUE THREAD

**Issue by GamersRepublic** [fadillzzz/tof-sih#38] opened 2024-04-20 14:50 UTC
Teleport to the closest nucleus needs to have the functionality to stop the player's movement and then calculate where to teleport and do teleport
If player's movement is in process - following option not works in most cases

Test: New account, mirroria where a lot of them available, bind any button to teleport, spam button within several seconds
When player is flying or falling - following option will work in ~ 1 of 10 cases

Test failed. Fix needed.

**Comment by fadillzzz** [comment] 2024-04-20 21:03
> Teleport to the closest nucleus needs to have the functionality to stop the player's movement and then calculate where to teleport and do teleport If player's movement is in process - following option not works in most cases
> 
> Test: New account, mirroria where a lot of them available, bind any button to teleport, spam button within several seconds When player is flying or falling - following option will work in ~ 1 of 10 cases
> 
> Test failed. Fix needed.

I couldn't reproduce this. Do you think you could post a video of this?



> Additional side notes:
> 
>     * Teleport option is not working when No Clip is turned on
> 
>     * Teleport option for chests is also not working in both specified behaviours (While movement & while noclip on)

These sound like separate issues that should be addressed in a different thread. Would you mind creating new issues for these? As a side note, I prefer to keep each GitHub issue to be specific to just one thing. It makes things easier to track that way, as conversation for a particular bug could drown out the other bugs mentioned within an issue, and they could end up being forgotten.

**Comment by fadillzzz** [comment] 2024-04-24 04:24
Teleport to nucleus while character is moving should be fine now. I've just pushed an update.

**Closed as completed** 2024-06-24 03:06 UTC
